### ISSUE TITLE
Issues withAffiliateService.affCommissions

### ISSUE THREAD

**Issue by acoyfellow** [justinhandley/infusionsoft-javascript-api#4]
`AffiliateService.affCommissions` is undefined

I forked, and realize it's because their XML API docs have it named "APIAffiliateService"

I renamed IAffiliateService to IAPIAffiliateService and it worked as expected

**Comment by justinhandley** [comment]
Hey - thanks for catching this!  I have updated and published this fix.  The original library we took from had quite a lot of old / renamed / incorrectly named methods and we did do a solid cleanup, but must have missed this one.  Updated in 3.0

**Comment by Kezzsim** [comment]
I think I have a similar problem with `./services/IAPIAffiliateService` which cannot be found on startup of my application. I'd try to change some of the requirements if this was something I was running on node locally but since it's going into a Docker Container my hands are kinda tied unless I pull and fork the entire application.

```
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
at Function.Module._load (internal/modules/cjs/loader.js:508:25)
 at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/home/node/app/node_modules/infusionsoft-javascript-api/infusionsoft/api.js:13:31)
```

**Comment by Kezzsim** [comment]
/Fixed by rolling back to 0.2.1
Does not work on Version 0.3.0 for me presently

**Comment by justinhandley** [comment]
@Kezzsim - I'll look at this today and get it fixed up.  Sorry for the inconvenience.

**Comment by ankush981** [comment]
Although it's a closed issue I wanted to say that I'm running into the same error as @Kezzsim mentioned: `Error: Cannot find module './services/IAPIAffiliateService'`. Version 0.2.0 seems to work for me, too.

**Comment by justinhandley** [comment]
OK, I just pushed a fix and updated to 0.3.1 - please confirm this new version is working for you?

**Comment by Kezzsim** [comment]
Yes
Thank you
I haven't had any problems with it since~

Do you know how long InfusionSoft plans on keeping XMLRPC active? They're missing the company endpoint and this was the only good solution in the interim. Just don't want them to shut the water off now that the faucet is working

**Comment by ankush981** [comment]
@justinhandley Yes, this works now. Thanks! :-)

**Comment by justinhandley** [comment]
As far as I’m aware Infusionsoft has no active plans for sunsetting XMLRPC since so many legacy applications are still using it.  Closing this out.
